steps:
  - uses: actions/checkout@v2

  - name: Set up Go
    uses: actions/setup-go@v2
    with:
      go-version: "1.23"

  - name: Tidy Go modules
    run: go mod tidy

  - name: Install dependencies
    run: go mod download

  - name: Build services
    run: |
      go build -o ingest ./cmd/ingest
      go build -o processing ./cmd/processing
      go build -o api ./cmd/api
